version: '2'
services:
  plex:
    container_name: pms
    image: plexinc/pms-docker:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISE_IP}
      - HOSTNAME=${INTERNAL_HOSTNAME}
    hostname: ${EXTERNAL_HOSTNAME}
    volumes:
      - ${CONFIG_VOLUME}:/config
      - ${TRANSCODE_VOLUME}:/transcode
      - ${MEDIA_VOLUME}:/data
